variables:
- group: demo-vm-deploy

trigger:
- master

jobs:
  - job: demo_image_build
    pool:
      vmImage: 'ubuntu-16.04'
    container:
      image: $(containerRegistry).azurecr.io/$(repositoryName):latest
      endpoint: demovmcontainer
    timeoutInMinutes: 360
    steps:
    - bash: 'sudo chown -R "$(whoami):" .'
      displayName: 'Changing the owner of /ansible folder to AzureDevops user'
      failOnStderr: true

    - bash: 'packer build -force packer/packer-build.json'
      displayName: 'Run Packer with Ansible build for alias '
      failOnStderr: true
      timeoutInMinutes: 360
      env:
        PACKER_CLIENT_ID: '$(packerClientId)'
        PACKER_CLIENT_SECRET: '$(packerClientSecret)'
        RESOURCE_GROUP_NAME: '$(resourceGroupName)'
        SUBSCRIPTION_ID: '$(subscriptionId)'
        GIT_REPO_SOURCE: '$(uipathDemoGitRepo)'
        GIT_TOKEN: $(githubToken)
        IMAGE_NAME: '$(managedImageName)_$(Build.BuildId)'
        SHARED_IMAGE_GALLERY: '$(sharedImageGalleryName)'
        SHARED_IMAGE_NAME: '$(managedImageName)'
        BUILD_NUMBER: '$(Build.BuildId)'
        DEFINITION_NAME: '$(Build.DefinitionName)'
        DEFINITION_VERSION: '$(Build.DefinitionVersion)'
        REPOSITORY_NAME: '$(Build.Repository.Name)'
        SOURCE_BRANCH: '$(Build.SourceBranch)'
        SOURCE_VERSION: '$(Build.SourceVersion)'
        PACKER_USERNAME: 'packer'
        MONGO_DB_CONNECTION_STRING: '$(mongoDBConnectionString)'

