---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - set_fact: 
        demo_folder: 'C:\UiPath\Demos\'
    - set_fact: 
        git_repo: "{{ lookup('env','GIT_REPO_SOURCE') }}"

    # Create required folders
    - name: Create demo folder
      win_file:
        path: "{{ demo_folder }}"
        state: directory

    - name: Copy PowerShell helper scripts to C:\Temp
      win_copy:
        src: PSscripts
        dest: C:\Temp

    - name: Copy ssh key for github access
      win_copy:
        src: id_rsa
        dest: C:\Temp\azure_devops
#
#    - name: Install Chrome, Firefox
#      win_chocolatey:
#        name:
#        - firefox
#        - googlechrome
#        - git
#        - python
#        - notepadplusplus
#        - github-desktop
#        state: present
#
#    - name: Set ssh-agent
#      win_service:
#        name: ssh-agent
#        start_mode: manual
#        state: started
#
#    - name: Disable inherited ACE's
#      win_acl_inheritance:
#        path: C:\Temp\azure_devops
#        state: absent
#
#    - name: Set the owner the ssh-key
#      win_owner:
#        path: C:\Temp\azure_devops
#        user: packer
#        recurse: no
#
#    - name: chmod
#      win_acl:
#        path: C:\Temp\azure_devops
#        user: packer
#        rights: Read,Write,Modify,FullControl,Delete
#        type: allow
#        state: present
#        inherit: ContainerInherit, ObjectInherit
#        propagation: 'None'
#
#    - name: sshkey add
#      win_shell: |
#        ssh -o StrictHostKeyChecking=no git@github.com
#        ssh-add C:\Temp\azure_devops
#        Add-Content -Path "C:\Program Files\Git\etc\ssh\ssh_config" "IdentityFile C:\Temp\azure_devops"
#        git clone {{git_repo}} {{ demo_folder }}
#    
#    - name: remove ssh key
#      win_file:
#        path: C:\Temp\azure_devops
#        state: absent
#
#
#    - name: Install ChromeDriver
#      win_chocolatey:
#        name: chromedriver
#        state: present
#
#    - name: Install Adobe Reader v11.0.10
#      win_chocolatey:
#        name: adobereader
#        version: '11.0.10'
#        ignore_checksums: yes # sha256:C438AC343381031CD47DD4ED966C8E86B2BCD5A1959F55C1C7D8C61920DD18BC
#
#    - name: Install JDK8
#      win_chocolatey:
#        name: jdk8
#
#    - name: Install JRE8
#      win_chocolatey:
#        name: jre8
#
#
#    # Powershell modules installation
#    - name: Ensure NuGET package provider
#      win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force
#
#    # chrome extension cannot be enabled automatically:
#    # https://support.google.com/chrome/thread/9069715?hl=en
#    - name: Install UiPath Studio
#      win_package:
#        path: https://download.uipath.com/versions/19.4.4/UiPathStudio.msi
#        arguments:
#        - /quiet
#        - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,RegisterService,JavaBridge,ChromeExtension
#        state: present
#        product_id: '{01D0B127-48B8-4EC7-87C1-41824830F50C}'
#
#    #Install SAP Components
#    - name: Install SAP Components
#      win_shell: C:\Temp\PSscripts\Install-SAPGUI.ps1
#
#