---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - name: Set facts
      set_fact: 
        demo_folder: 'C:\UiPath\Demos\'
        config_folder: 'C:\UiPath\config\'
        git_repos: "{{ lookup('env','GIT_REPO_SOURCE').split(',') }}"
        git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
        mongoDBConnectionString: "{{ lookup('env', 'MONGO_DB_CONNECTION_STRING') }}"

    # Create required folders
    - name: Create demo folder
      win_file:
        path: "{{ demo_folder }}"
        state: directory

    - name: Create config folder
      win_file:
        path: "{{ config_folder }}"
        state: directory

    - name: Create initial config
      win_copy:
        content: "{'mongoDBConnectionString': '{{ mongoDBConnectionString }}'}"
        dest: "{{ config_folder }}dsf.json"

    - name: Copy PowerShell helper scripts to C:\Temp
      win_copy:
        src: PSscripts
        dest: C:\Temp

    - name: Copy Config files to C:\Temp
      win_copy:
        src: configFiles
        dest: C:\Temp

    - name: Install git client
      win_chocolatey:
        name:
        - git
        state: present

    - name: Git clone demo repositories
      win_shell: |
        cd {{demo_folder}}
        git clone https://{{git_token}}@github.com/{{ item }}
      loop:
        "{{ git_repos }}"

    - name: Install Chrome, Firefox, python
      win_chocolatey:
        name:
        - firefox
        - googlechrome
        - python
        - notepadplusplus
        - github-desktop
        state: present

    - name: Install ChromeDriver
      win_chocolatey:
        name: chromedriver
        state: present

    - name: Install Adobe Reader v11.0.10
      win_chocolatey:
        name: adobereader
        version: '11.0.10'
        ignore_checksums: yes # sha256:C438AC343381031CD47DD4ED966C8E86B2BCD5A1959F55C1C7D8C61920DD18BC

    - name: Install JDK8
      win_chocolatey:
        name: jdk8

    - name: Install JRE8
      win_chocolatey:
        name: jre8

    # Powershell modules installation
    - name: Ensure NuGET package provider
      win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force

    # chrome extension cannot be enabled automatically:
    # https://support.google.com/chrome/thread/9069715?hl=en
    - name: Install UiPath Studio
      win_package:
        path: https://download.uipath.com/versions/19.10.3/UiPathStudio.msi
        arguments:
        - /quiet
        - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,RegisterService,JavaBridge,ChromeExtension
        state: present
        product_id: '{2000F340-CF98-4591-A099-8D781BF4B593}'
    
    - name: Autostart UiPath Robot immediately
      win_shell: sc.exe config UiRobotSvc start=auto

    #Install SAP Components
    - name: Install SAP Components
      win_shell: C:\Temp\PSscripts\Install-SAPGUI.ps1

    - name: Install Access Database Engine 2010
      win_chocolatey:
        name:
        - made2010
        state: present
        ignore_checksums: yes # 15E5151BDE13AA6756B7D0C74DB5831932559FC4A60D1F7A43ED1F44E8102558

    - name: install pip modules
      win_shell: |
        pip install pymongo
        pip install azure
        pip install requests

    - name: Download nuget pkg
      win_get_url:
        url: https://presalesdemobuild.blob.core.windows.net/binaries/uipath.machinelearningextractor.1.0.0-beta.540392.nupkg
        dest: C:\Program Files (x86)\UiPath\Studio\Packages\uipath.machinelearningextractor.1.0.0-beta.540392.nupkg
    
    - name: Disable Windows sounds
      win_regedit:
        path: HKCU:\AppEvents\Schemes
        name: 
        data: .None