---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - name: Set facts
      set_fact: 
        demo_folder: 'C:\UiPath\Demos\'
        config_folder: 'C:\UiPath\config\'
        git_repos: "{{ lookup('env','GIT_REPO_SOURCE').split(',') }}"
        git_token: "{{ lookup('env', 'GIT_TOKEN') }}"
        blob_conn_string: "{{ lookup('env', 'BLOB_CONN_STRING') }}"
      no_log: True

    # Create required folders
    - name: Create demo folder
      win_file:
        path: "{{ demo_folder }}"
        state: directory

    - name: Create config folder
      win_file:
        path: "{{ config_folder }}"
        state: directory

    - name: Copy PowerShell helper scripts to C:\Temp
      win_copy:
        src: PSscripts
        dest: C:\Temp

    - name: Copy Config files to C:\Temp
      win_copy:
        src: configFiles
        dest: C:\Temp

    - name: Install git client
      win_chocolatey:
        name:
        - git
        state: present

    - name: Git clone demo repositories
      win_shell: |
        cd {{demo_folder}}
        git clone https://{{git_token}}@github.com/{{ item }}
      loop:
        "{{ git_repos }}"
      no_log: True

    - name: Install Firefox, NP++, github-desktop
      win_chocolatey:
        name:
        - firefox
        - notepadplusplus
        - github-desktop
        state: present

    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        pinned: yes
        state: present
        ignore_checksums: yes

    - name: Install python
      win_chocolatey:
        name: python3
        version: 3.6.8
        state: present

    - name: Add Azure Storage PowerShell module
      win_psmodule:
        name: Azure.Storage
        state: present

    - name: Install ChromeDriver
      win_chocolatey:
        name: chromedriver
        state: present

    - name: Install Adobe Reader v11.0.10
      win_chocolatey:
        name: adobereader
        version: '11.0.10'
        ignore_checksums: yes # sha256:C438AC343381031CD47DD4ED966C8E86B2BCD5A1959F55C1C7D8C61920DD18BC

#    - name: Install JDK8
#      win_chocolatey:
#        name: jdk8
#
#    - name: Install JRE8
#      win_chocolatey:
#        name: jre8

    # Powershell modules installation
    - name: Ensure NuGET package provider
      win_shell: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force

    # chrome extension cannot be enabled automatically:
    # https://support.google.com/chrome/thread/9069715?hl=en
    - name: Install UiPath Studio
      win_package:
        path: https://download.uipath.com/versions/19.10.4/UiPathStudio.msi
        arguments:
        - /quiet
        - ADDLOCAL=DesktopFeature,Robot,Packages,Studio,UseAgentDesktop,StartupLauncher,RegisterService,JavaBridge,ChromeExtension
        state: present
        product_id: '{84EFE417-2716-4CF3-B5B1-A907FB6498AE}'

    - name: Install UiPath Remote Runtime
      win_package:
        path: https://download.uipath.com/versions/19.10.4/UiPathRemoteRuntime.msi
        arguments:
          - /quiet
          - ADDLOCAL=RemoteRuntime,RemoteRuntimeTask
        state: present
        product_id: '{2F9DD2FF-128B-4957-9035-3DB2F80B5E51}'
    
    - name: Set service startup mode to auto and ensure it is started
      win_service:
        name: UiRobotSvc
        start_mode: auto
        state: started

    #Install SAP Components
    - name: Install SAP Components
      win_shell: C:\Temp\PSscripts\Install-SAPGUI.ps1 -ConnectionString "{{ blob_conn_string }}"
      args:
        creates: "C:\\Program Files (x86)\\SAP"
      no_log: True

    - name: Install Access Database Engine 2010
      win_chocolatey:
        name:
        - made2010
        state: present
        ignore_checksums: yes # 15E5151BDE13AA6756B7D0C74DB5831932559FC4A60D1F7A43ED1F44E8102558

    - name: install pip modules
      win_shell: |
        pip install pymongo
        pip install azure
        pip install requests
        pip install azure-mgmt-resource
        pip install msrestazure
        pip install azure-keyvault-secrets 
        pip install azure-keyvault-keys
        pip install azure-keyvault-certificates
        pip install azure-identity

    - name: Download nuget pkg
      win_get_url:
        url: https://presalesdemobuild.blob.core.windows.net/binaries/uipath.machinelearningextractor.1.0.0-beta.540392.nupkg
        dest: C:\Program Files (x86)\UiPath\Studio\Packages\uipath.machinelearningextractor.1.0.0-beta.540392.nupkg
    
    - name: Import Insights Orchestrator certificate 1/2
      win_certificate_store:
        path: C:\Temp\configFiles\insightsAzure.cer
        store_name: Root
    
    - name: Import Insights Orchestrator certificate 2/2
      win_certificate_store:
        path: C:\Temp\configFiles\orchestratorCertificate.cer
        store_name: Root
