---
- name: Test Ansible on Azure base VM
  hosts: all
  gather_facts: yes
  tasks:
    - set_fact: 
        demo_folder: 'C:\UiPath\Demos\'

    - name: Install Access Database Engine 2010
      win_chocolatey:
        name:
        - made2010
        state: present

    - name: install pymongo
      win_shell: |
        pip install pymongo
        pip install azure
        pip install requests

